name: flutter_application_generator
description: A starter CLI for creating apps using FlutterApplicationTemplate.
version: 1.0.0
repository: https://github.com/nventive/FlutterApplicationTemplate

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  cli_completion: ^0.5.0
  mason_logger: ^0.3.2
  pub_updater: ^0.5.0
  archive: ^4.0.2
  http: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  lints: ^5.1.1
  test: ^1.24.0

executables:
  flutter_application_generator:
