name: mvvm_lints
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.7.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  custom_lint_builder: ^0.7.3
  analyzer: ^7.6.0
  analyzer_plugin: ^0.12.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
